# This file was auto generated by Valama 0.1.2. Do not modify it.
set(project_name "Lirab")
set(Lirab_VERSION "0.4.0")
set(required_pkgs
  "cairo"
  "glib-2.0"
  "gobject-2.0"
  "gtk+-3.0"
  "pango"
  "pangocairo"
  "sqlite3"
)
set(srcfiles
  "src/main.vala"
  "src/lirab.vala"
  "src/lirabdb.vala"
  "src/hauptfenster.vala"
  "src/mittelfenster.vala"
  "src/mitteledit.vala"
  "src/rationfenster.vala"
  "src/rationedit.vala"
  "src/auswertung.vala"
  "src/rationtab.vala"
  "src/rationtabkuh.vala"
  "src/rationtabfaerse.vala"
  "src/rationtabbulle.vala"
  "src/config.vala"
)
set(vapifiles
)
set(uifiles
  "ui/lirab.ui"
)
